In [1]:
import numpy as np
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8, 16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [2]:
a1 + a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)
print(a4)
print(a3)
print(a4 + a3)

[[0 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
