In [6]:
import numpy as np

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.ones((3,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
type(arr3)
type(arr1)
type(arr2)

numpy.ndarray

In [11]:
arr4 = np.identity(2)
arr4

array([[1., 0.],
       [0., 1.]])

In [12]:
arr5 = np.arange(1,20,2)
arr5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
arr6 = np.linspace(0,100,11)
arr6

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [14]:
arr7 = arr6.copy()
arr7

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
arr3.shape

(3, 3)

In [16]:
arr2.ndim

2

In [17]:
arr7.size

11

In [18]:
arr7.itemsize

8

In [19]:
arr1.dtype

dtype('int64')

In [20]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [21]:
listA = range(100)
listA

range(0, 100)

In [22]:
import sys
print(sys.getsizeof(28) * len(listA))

2800


In [24]:
print(arr2.itemsize*arr2.size)

48


In [29]:
import time
x = range(1000000)
y = range(1000000, 2000000)

stTime = time.time()
ans = [(x,y) for x,y in zip(x,y)]
print(time.time() - stTime)

0.4078369140625


In [31]:
x1 = np.arange(1000000)
y1 = np.arange(1000000, 2000000)
stTime = time.time()
print(time.time() - stTime)


0.00012922286987304688
