In [18]:
"""Create this array:
[10, 20, 30, 40, 50]
using:
np.array()
np.arange()
np.linspace()
"""

'Create this array:\n[10, 20, 30, 40, 50]\nusing:\nnp.array()\nnp.arange()\nnp.linspace()\n'

In [ ]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.arange(10, 60, 10)
arr3 = np.linspace(10, 50, 5)
arr4 = np.zeros((5,5))
arr5 = np.ones((5,5))
arr6 = np.identity(5)
arr7 = np.random.randint(1,100,20)

In [20]:
arr7

array([93, 50, 70, 76, 66, 14, 48, 87, 11, 58, 20, 19,  9, 70, 93, 88, 39,
       43,  9, 22], dtype=int32)

In [24]:
arr = np.arange(1,21)
arr01 = np.arange(5,10)
arr01

array([5, 6, 7, 8, 9])

In [28]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr[arr%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
arr[(arr > 10) & (arr%2 == 0)]

array([12, 14, 16, 18, 20])

In [33]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
arr[:,4]

array([ 5, 10, 15, 20, 25])