In [34]:
import numpy as np
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr2 = arr1.reshape(5,5)

In [36]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
# to get column = 1
arr2[:,0:1]

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [38]:
# to get column = 3
arr2[:,2]

array([ 2,  7, 12, 17, 22])

In [39]:
# to get 18, 19, 23, 24
arr2[3:5, 3:5]

array([[18, 19],
       [23, 24]])

In [40]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [41]:
arr3 = np.arange(10, 20, 2)
arr4 = np.arange(20, 30, 2)
arr3

array([10, 12, 14, 16, 18])

In [42]:
arr4-arr3

array([10, 10, 10, 10, 10])

In [43]:
arr3*2

array([20, 24, 28, 32, 36])

In [44]:
arr3 > 15

array([False, False, False,  True,  True])

In [45]:
arr3.dot(arr4)

np.int64(1720)

In [46]:
arr3.max()

np.int64(18)

In [47]:
arr4.min()

np.int64(20)

In [48]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr2.min(axis = 1)

array([ 0,  5, 10, 15, 20])

In [50]:
arr2.mean()

np.float64(12.0)

In [51]:
arr2.std()

np.float64(7.211102550927978)

In [52]:
np.sin(arr2)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])