In [2]:
import numpy as np
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
arr2 = arr1.reshape(5,5)

In [11]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# to get column = 1
arr2[:,0:1]

array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [ ]:
# to get column = 3
arr2[:,2]

array([ 2,  7, 12, 17, 22])

In [ ]:
# to get 18, 19, 23, 24
arr2[3:5, 3:5]

array([[18, 19],
       [23, 24]])

In [23]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
