In [5]:
import numpy as np
arr1 = np.arange(10)
arr2 = arr1.reshape(5, 2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
arr2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr2.ndim

2

In [8]:
arr2.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])